### ISSUE TITLE
Android: Crash within OnMAMResume() using SDK version 1.1.0.0

### ISSUE THREAD

**Issue by JoeM-RP** [msintuneappsdk/intune-app-sdk-xamarin#1]
Xamarin.Forms (PCL) Android app with Intune SDK integration crashes on launch within OnMAMResume. Console output:

```
04-28 11:21:27.099 I/MonoDroid( 1938): UNHANDLED EXCEPTION:
04-28 11:21:27.114 I/MonoDroid( 1938): System.InvalidProgramException: Invalid IL code in Xamarin.Forms.Platform.Android.FormsAppCompatActivity:OnMAMResume (): IL_001e: brfalse.s IL_005a
04-28 11:21:27.114 I/MonoDroid( 1938):   at Microsoft.Intune.Mam.Client.Support.V7.App.MAMAppCompatActivityBase.n_OnMAMResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in C:\Bld\115\123\Sources\obj\AnyCPU\Release\Microsoft.Intune.Android\generated\src\Microsoft.Intune.Mam.Client.Support.V7.App.MAMAppCompatActivityBase.cs:753 
04-28 11:21:27.114 I/MonoDroid( 1938):   at (wrapper dynamic-method) System.Object:55554b7b-f8e4-4ded-942d-ec97e374e92c (intptr,intptr)
```

Verified on:
- Nexus 5X
- Visual Studio Emulator for Android v 1.1.1207.2 simulating 5.5" Marshmallow (6.0.0) XXHDPI Phone, API Level 23, 1GB (Similar to Motorola Moto X Play)

Developer Configuration:
- Visual Studio 2017 15.1 (26403.7) 
- Xamarin 4.4.0.34 (3f99c5a)
- Xamarin.Android SDK 7.2.0.7 (b16fb82)

**Comment by paulryan** [comment]
I see it working with FormsApplicationActivity but throwing this error for FormsAppCompatActivity. The latter provides the support for TabLayoutResource and ToolbarResource.

**Comment by hallkvist** [comment]
I've got the same problem! Did you find a solution?

**Comment by paulryan** [comment]
Glad to hear that it's not just me. Unfortunately, I've not got a solution but this is likely just because I've been working on other projects since I encountered this. Please do post if you find a solution!

**Comment by JoeM-RP** [comment]
No resolution from me either - ended up scrapping the SDK integration and forgoing the features it provides

**Comment by msintuneappsdk** [comment]
@JoeM-RP @paulryan @hallkvist Intune's Xamarin support is currently in preview. Please reach out to msintunesdk@microsoft.com and we can investigate further.

**Comment by hallkvist** [comment]
@msintuneappsdk  Well... I already raised another issue to the product group, but the response was "... the project had set dormant for a full year". So I guess it wouldn't make sense to raise this either.

**Comment by reutann** [comment]
@JoeM-RP, @paulryan, @hallkvist - this is resolved in the latest versions of the remapper package and the Android DLL found in this repo. Please try them out and let us know what you think!
