### ISSUE TITLE
Need a sample application for Intune app sdk in Xamaring Bindings for Xamarin forms android

### ISSUE THREAD

**Issue by Aparnakalyani** [msintuneappsdk/intune-app-sdk-xamarin#14]
I have an Android application developed in Xamarin forms, and i have to integrate the intune App SDK. I am trying to follow the Guide, but I would also like to have a sample app on the  Intune Integration -Xamarin Bindings for Android APP in Xamarin Forms.

I tried with App Wrapping Tool to wrap the Xamarin application, but the app is crashing. 
Can anyone help me out with sample application for Xamarin android?

**Comment by msintuneappsdk** [comment]
Hi @Aparnakalyani, thanks for your post. The Intune App Wrapping Tool for Android does not support Xamarin based apps so you would have to use the Intune Xamarin Bindings. We are working to get some sample apps released for Xamarin.Android and Forms and are targeted for releasing in Q4 2018. They will be posted on the msintuneappsdk GitHub once they are available.
