### ISSUE TITLE
MAM SDK cannot find ADAL tokens if they come from a test tenant (eg. my.onmicrosoft.com)

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#16]
We have a test tenant with that format. I can successfully login with ADAL and acquire tokens but, MAM SDK cannot find them.

Any ideas?

**Comment by Kyle-Reis** [comment]
Hey @alexrainman, this is on iOS?

**Comment by alexrainman** [comment]
Yes, as Android give the option to provide the SDK where the token is coming from.

**Comment by Kyle-Reis** [comment]
Are you specifying any ADAL settings under the IntuneMAMSettings dictionary in the app's Info.plist or dynamically via our override APIs?

**Comment by alexrainman** [comment]
I do both but I think the ones under IntuneMAMSettings are not used at all as I use ADAL for authentication and I have the settings in the authenticator class.

Which override APIs are you referring?

**Comment by Kyle-Reis** [comment]
I'm referring to the IntuneMAMPolicyManager.Instance.AAD*Override properties. Do you set any of those? What do you have specified for an authority under the IntuneMAMSettings?

**Comment by alexrainman** [comment]
NO, I am not using the AAD overrides.

Authority looks like this:

```
https://login.windows.net/tenantid
```

The thing is as soon as I change the tenantid to our production environment then everything works as expected.

**Comment by Kyle-Reis** [comment]
Are you using a custom client ID as well?

**Comment by alexrainman** [comment]
Custom client ID?

**Comment by Kyle-Reis** [comment]
When your app authenticates, it must provide a client ID to AAD, have you specified that client ID in the IntuneMAMSettings?

**Comment by alexrainman** [comment]
Yes. I dont have an issue with that. It is not the client id. I get Auth Required, mam sdk cannot find the tokens.

**Comment by Kyle-Reis** [comment]
Do you use the same client ID when changing tenants?

If so, in the app registration for this client ID in Azure Portal, is the following set?

availableToOtherTenants = true

**Comment by alexrainman** [comment]
What availableToOtherTenants means?
For now I switch client ID.

**Comment by Kyle-Reis** [comment]
availableToOtherTenants means the client app is allowed to authenticate and access resources on other tenants. If this setting is not enabled, the app will only be able to access resources on the tenant where its app registration is defined.

The client ID you switch to is defined in the test tenant? Has it been granted access to the MAM Service API using [these steps](https://docs.microsoft.com/intune/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional)? When you change the client IDused to acquire a token in the app code, do you also update the value in the IntuneMAMSettings to match?

**Comment by alexrainman** [comment]
Do you have to do anything specific to make an app id available in other tenants? I mean from configuration perspective in the tenant itself.

Yeah, i update app id eveywhere and run the app in a clean device.

**Comment by Kyle-Reis** [comment]
If you look at the app registration manifest in Azure portal, you should see the following set:

 "availableToOtherTenants": true

I believe this setting is enabled by default.

Since you are changing the client ID to one that is defined in the test tenant, this is likely not your issue. When you change the client ID, do you also change the redirect URI to what is defined for the app registration in the test tenant?

**Comment by alexrainman** [comment]
Yes. I also change that. What i see during debug is that i am actually getting a token. It seems MAM SDK doesn’t understand it or cannot find it.

**Comment by Kyle-Reis** [comment]
Is the app signed the same when you test using the test tenant as when using the production tenant?

**Comment by alexrainman** [comment]
Yes :)

**Comment by Kyle-Reis** [comment]
Hey Alex, are you still having this issue?

**Comment by alexrainman** [comment]
Yes.

**Comment by Kyle-Reis** [comment]
If you switch to calling LoginAndEnrollAccount, with the ADAL settings configured for you your test tenant under IntuneMAMSettings, what happens?

**Comment by Kyle-Reis** [comment]
Hey @alexrainman, checking in again to see if you’re still having trouble here.

**Comment by alexrainman** [comment]
Yes. Still doesn’t work. We implemented everything in our prod tenant because of this issue.

**Comment by Kyle-Reis** [comment]
@alexrainman have you tried the LoginAndEnrollAccount test I suggested on Apr 18?

**Comment by meghandaly** [comment]
Closing as there is not enough to continue the investigation and it appears that this issue is obsolete.
