### ISSUE TITLE
Getting Error "This app has not been set up for you to use. Contact your IT administrator for Help." Only on Android

### ISSUE THREAD

**Issue by quantumarun** [msintuneappsdk/intune-app-sdk-xamarin#17]
Hi Team,
I am able to integrate Intune SDK for Xamarin successfully for both iOS and Android.
On iOS things are working fine as when i can see the device/user details on Intune portal for the app as will as App Protection Policies are working.

But on Android i am always getting the alert "This app has not been set up for you to use. Contact your IT administrator for Help."
This happens after the Azure Sign-Up page is authenticated on App Launch. I am not using any ADAL configuration as i don't have ADAL authentication in my App.

I have followed the guide at https://docs.microsoft.com/en-us/intune/app-sdk-xamarin and for MAM-WE i have defined Default settings in manifest file as defined in the section "Requiring Intune app protection policies in order to use your Xamarin-based Android LOB app (optional)" at https://docs.microsoft.com/en-us/intune/app-sdk-xamarin.

Am i missing any configuration. Since ADAL authentication is used in my App i am not doing any ADAL settings.

Application is based on Xamarin Forms with below configuration:
Xamarin.Forms: 3.4.0.1009999
Microsoft.Intune.MAM.Remapper.Tasks: 0.1.4119.2
Microsoft.Intune.MAM.Xamarin.Android: 3.0.4035.4

**Comment by quantumarun** [comment]
Answer to both questions is YES.
Also i could not see any details under Monitor as well for Device install status and User install status.

<img width="1701" alt="screen shot 2019-02-04 at 9 27 08 am" src="https://user-images.githubusercontent.com/5046311/52261379-a7b8d780-2942-11e9-992e-e7bd796055cb.png">
<img width="1695" alt="screen shot 2019-02-04 at 9 27 18 am" src="https://user-images.githubusercontent.com/5046311/52261380-a8516e00-2942-11e9-92b1-1d39a9940ea4.png">

**Comment by quantumarun** [comment]
Team,
Any help on this?

**Comment by aanavath** [comment]
HI @quantumarun, can you please send an email to msintuneappsdk@microsoft.com with some of the following information: 
- What version of the Android Company Portal is on the device? Are you using the latest one?
- Once Company Portal is installed, can we get the logs sent to us using these instructions: https://docs.microsoft.com/en-us/intune-user-help/send-logs-to-your-it-admin-by-email-android 
- Who is the customer? Have you opened an ICM?

**Comment by quantumarun** [comment]
As said details send to the email address mentioned.

**Comment by msintuneappsdk** [comment]
Closing issue as it was reported via email that the app is indeed getting policies after some time. The lack of reporting is likely due to these apps being deployed as Available or With or Without Enrolment.
