### ISSUE TITLE
Application developers call IntuneMAMDataProtectionManager APIs for all Org Data.

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#19]
Can you provide an example on how to use this class?

https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/blob/master/Headers/IntuneMAMDataProtectionManager.h

**Comment by Kyle-Reis** [comment]
Hey @alexrainman, here is some info on these APIs: https://docs.microsoft.com/intune/app-sdk-ios#shared-data. Only apps which support multi-identity (managed + unmanaged personal accounts) should need to call these APIs. Is that the case for your app?

**Comment by alexrainman** [comment]
Yeah, we may have that use case. Thanks for sharing.
