### ISSUE TITLE
Microsoft.Intune.MAM.iOS insufficient binding of the native lib

### ISSUE THREAD

**Issue by LDan1117** [msintuneappsdk/intune-app-sdk-xamarin#2]
Hi!

I have tried to integrate the Intune App SDK Xamarin component with a Xamarin.iOS app and encountered an issue. The contract exposed by the native library (Intune App SDK for iOS) differs from the one of Xamarin component. You can see it in attached screenshots.
IntuneMAMConfig and IntuneMAMConfigManager are missing in the Xamarin component (not only these types).
![1](https://user-images.githubusercontent.com/15735136/34438743-9c4e164a-ecb1-11e7-8da0-18a83f89199b.png)
![1](https://user-images.githubusercontent.com/15735136/34438758-b0bda7bc-ecb1-11e7-9859-dd431a500e8d.png)

Also, pay attention to the version of Microsoft.Intune.MAM.iOS assembly. Why is it 1.0.0.0? It seems to me that the version should be 1.1.0.0.
Missing types prevent a Xamarin.iOS app from retrieving custom configuration policies from the Intune admin console.

**Comment by Kyle-Reis** [comment]
Hey @LDan1117, this should be addressed in the current version (2.1.0.0). Version 1.1.0.0 was released well before the native APIs you are referencing became available. Note: The assembly version issue you mentioned was not addressed in 2.1.0.0, so you may notice they are still 1.0.0.0, but we've noticed the issue and will be updating the assembly versions as well moving forward

**Comment by Kyle-Reis** [comment]
The assembly versioning issue has also been addressed in the latest release. We have moved to NuGet packages, as Xamarin components are being deprecated. Please see the updated documentation at https://docs.microsoft.com/intune/app-sdk-xamarin
