### ISSUE TITLE
Feature request: make Device PIN required in Android on Intune MAM only scenario if "Encrypt App Data" setting in the Intune App Policy is set to "Yes"

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#20]
If "Encrypt App Data" setting in the Intune App Policy is set to "Yes" then, a Device PIN will be required in iOS. The SDK can determine the existence of a device PIN but not its complexity, which is fine.

If device PIN is not enabled, the access to MAM SDK enabled apps will be blocked.

We need the same "user experience"/behavior in Android.
No matter if the Device PIN is not used for encryption, it slow down attackers.

**Comment by alexrainman** [comment]
I found a way to do this in Android but we don't want to leave that into the hands of our developers but in the SDK we trust.

**Comment by msintuneappsdk** [comment]
@alexrainman Thanks for your feedback. We don't have any plans to enforce a device PIN using app protection policies today. The reason for the difference between iOS and Android is more of a platform requirement than a design choice. 

In the future, Feature Requests should be added to [Intune UserVoice](https://microsoftintune.uservoice.com/forums/291681-ideas?category_id=148986). GitHub issues is ideal for bugs or errors when using our Intune developer tools.
