### ISSUE TITLE
Microsoft Intune integration with MVVM Cross in Xamarin Android

### ISSUE THREAD

**Issue by sateeshmcs** [msintuneappsdk/intune-app-sdk-xamarin#21]
Hello,

Is there any samples or useful links for Intune integration with mvvm cross in Android.
I didn't find any wrapper for Intune + MVVMCross.

Unfortunately MVVMCross requires you to inherit from it's own base classes for things like application and activities etc. So as it stands we can't see how we achieve Intune integration without either rewriting our to not use MVVMCross or to take a fork of MVVMCross and change it to derive from MAM classes.

Is there no way to support Intune in Android in a similar way to iOS that will allow us to use existing code?

Regards,
Sateesh taddi

**Comment by msintuneappsdk** [comment]
Hi @sateeshmcs, in the past our team has investigated developing apps with MVVM Cross and have determined that they cannot exist with MAM integration. Another customer who had developed MVVM Cross apps is investigating using MVVM Light or Xamarin.Forms itself. We will update our documentation to clarify this.
