### ISSUE TITLE
Can the Company Portal requirement been removed?

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#22]
Now that Managed Google Play is supported without device enrollment this requirement should be removed. It may solve the debugging issue under API 23 and above.

**Comment by msintuneappsdk** [comment]
Hi @alexrainman, regardless of Managed Google Play being supported without device enrollment, the Company Portal on Android still remains a requirement to receive App Protection Policies for apps integrated with the Intune SDK. Here is some documentation that [calls out this existing requirement](https://docs.microsoft.com/en-us/intune/end-user-mam-apps-android). UserVoice is a better channel than GitHub for suggesting and voting for features, and the Company Portal requirement on Android has been listed as a UserVoice item [here, which you may want to upvote](https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/14740500-mam-without-enrolment-android-remove-requiremen). We find that GitHub is better suited for specific issues with our developer tools.
