### ISSUE TITLE
Microsoft.Intune.MAM: SDK could not access the user's AAD token For Xamarin iOS app

### ISSUE THREAD

**Issue by AkshaySLB** [msintuneappsdk/intune-app-sdk-xamarin#26]
I have implemented Microsoft.Intune.MAM.Xamarinn.iOS package into my Xamarin solution and have followed the steps mentioned in the document for enabling Keychain and entered in Entitlements.plist. ADAL is working fine and I'm able to get token. Somehow Microsoft.Intune.MAM package is not able to get AAD token. I'm getting below error:

> The operation failed because the SDK could not access the user's AAD token.  The application should prompt the user for credentials to refresh the user's AAD token.

**info.plist contains:** 
IntuneMAMSettings
LSApplicationQueriesSchemes

**Entitlements.plist contains:** 
$(AppIdentifierPrefix)my app identifier
$(AppIdentifierPrefix)com.microsoft.intune.mam
$(AppIdentifierPrefix)com.microsoft.adalcache

Version for Microsoft.Intune.MAM.Xamarinn.iOS I'm using is: 10.0.7 however I have tried it with 10.0.1 also.

**Comment by Kyle-Reis** [comment]
Hey @AkshaySLB, which version of ADAL for .Net are you using? Did you follow the instructions to set the KeychainSecurityGroup on the AuthenticationContext mentioned in step 4 below?

https://docs.microsoft.com/intune/app-sdk-xamarin#enabling-intune-app-protection-polices-in-your-ios-mobile-app

Note: that property requires that the Team ID prefix is included. So the value you set should looks something like [Team ID].com.microsoft.adalcache

**Comment by AkshaySLB** [comment]
I'm using 4.5.1 version for ADAL and yes I have followed the steps mentioned in the document but I'm using `IntuneMAMEnrollmentManager.Instance.RegisterAndEnrollAccount(string identity);` where I'm sending "identity" after successful login.

Entitlements.plist doesn't contains Team Id and instead it shows $(AppIdentifierPrefix) when I'm adding identifiers.

**Comment by Kyle-Reis** [comment]
Your entitlements file looks good. At build time, the $(AppIdentifierPrefix) will get replaced with your team ID + "." The team ID is taken from your provisioning profile.

When you set the KeychainSecurityGroup property in code, you need to include the app ID prefix. If you are working on Mac, you should be able to find the prefix by running the following terminal command: 

   codesign -d --entitlements :- [PATH_TO_COMPILED_APP]

Replace [PATH_TO_COMPILED_APP] with the path to your compiled ".app" file. You should get a list of entitlements similar to the one you shared above, prefixed by your team ID and a "."

Note: if you sign different versions of your app with different provisioning profiles, you'll need to be sure to update the value you assign to the KeychainSecurityGroup property. The ADAL team is working on introducing a new property which addresses this problem and does not require that the app ID prefix is included.

**Comment by AkshaySLB** [comment]
Yes, I'm able to see actual team Id using mentioned command.

Now coming back to our issue - how to fix this error: `The operation failed because the SDK could not access the user's AAD token. The application should prompt the user for credentials to refresh the user's AAD token.`

Is there any way I can check if com.microsoft.adalcache have AAD token or not?

**Comment by Kyle-Reis** [comment]
Have you tried including the team ID prefix in the value you assign to the AuthenticationContext’s KeychainSecurityProperty?

**Comment by AkshaySLB** [comment]
Yes I tried but it did not worked

**Comment by AkshaySLB** [comment]
any updates on this?

**Comment by AkshaySLB** [comment]
@Kyle-Reis we are stuck because of this issue, can you please let us know updates on this issue?

**Comment by Kyle-Reis** [comment]
Hey @AkshaySLB, by any chance is your app authenticating via the MS Authenticator app?

**Comment by dathway** [comment]
> Your entitlements file looks good. At build time, the $(AppIdentifierPrefix) will get replaced with your team ID + "." The team ID is taken from your provisioning profile.
> 
> When you set the KeychainSecurityGroup property in code, you need to include the app ID prefix. If you are working on Mac, you should be able to find the prefix by running the following terminal command:
> 
> codesign -d --entitlements :- [PATH_TO_COMPILED_APP]
> 
> Replace [PATH_TO_COMPILED_APP] with the path to your compiled ".app" file. You should get a list of entitlements similar to the one you shared above, prefixed by your team ID and a "."
> 
> Note: if you sign different versions of your app with different provisioning profiles, you'll need to be sure to update the value you assign to the KeychainSecurityGroup property. The ADAL team is working on introducing a new property which addresses this problem and does not require that the app ID prefix is included.

@Kyle-Reis Where is the AuthenticationContext where you set the KeychainSecurityGroup property? It wasn't clear to me from the docs where I set this, or what it looks like. 

A bit of background on the app I'm working on: We are using Webview in Xamarin Forms and integrating with ADAL. Our goal here is to get the webview used in the app to be able to work with InTune. Step 4 in the docs you've linked above, mentions setting this KeychainSecurityGroup for ADAL apps. Any examples or additional info you have on this would be appreciated Thanks.

**Comment by Kyle-Reis** [comment]
Hey @dathway. Just to clarify, you are integrating ADAL using this NuGet package?

https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory

If so, which version are you using?

**Comment by dathway** [comment]
@Kyle-Reis We are integrating the ADAL nuget package in Identity Server 4. We have setup IDS4 as a federated gateway, since we need to enrich some claims which are not in Azure, for our app. The problem we are facing is a conditional access policy set in InTune, is preventing our Webview component in mobile, from receiving the the access token back from Azure AD. If we remove Webview, we are able to bypass this restriction, but we thought perhaps installing the InTune SDK in our mobile app might allow us to get around this security policy somehow.

It's becoming clear to me that the steps outlined in the docs for only for Xamarin apps connecting directly to AzureAD, and our scenario doesn't fit.

**Comment by Kyle-Reis** [comment]
@dathway, thanks for clarifying. It sounds like your issue is not related to the Intune SDK or our Xamarin bindings, but rather a CA policy that is set up in your environment which requires that authentication take place within a particular browser(s)

@AkshaySLB, are you still facing your issue?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. If you’re still experiencing this problem, please reopen!
