### ISSUE TITLE
MAM SDK cannot find tokens from one Application ID while it can for other

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#27]
I have this app with ADAL and MAM integrated. We registered a brand new application on AAD but MAM SDK cannot find the tokens ADAL acquires using that application id while it can find tokens acquired with another app id that is already proven to work.

I compared the tokens from both app ids and I cannot find any differences.

We checked the AAD apps and couldn't find anything there neither.
We tried providing permissions consent again. Didn't work.

Any ideas?

**Comment by Kyle-Reis** [comment]
Hey @alexrainman, what do you mean by "providing permissions consent"? Did you update the client ID in both your app's acquire token call and the Intune settings? Did you also update the Redirect URI to match what is specified in AAD under the new app registration?

**Comment by alexrainman** [comment]
In AAD you have to consent permissions for them to work and yes, app id and redirect url are the same in adal call and mam settings on info.plist.

**Comment by Kyle-Reis** [comment]
Hey @alexrainman were you able to figure this out? If not, what happens if you use LoginAndEnrollAccount with all the same AAD settings? Are you able to successfully enroll then?

**Comment by alexrainman** [comment]
Yes. The problem is MSFT added a new API that needs to be included in the permissions of every AAD app so it works with Intune.
