### ISSUE TITLE
Visual studio 2019 Android build fails on ResolveAssemblies task

### ISSUE THREAD

**Issue by pete-cho** [msintuneappsdk/intune-app-sdk-xamarin#28]
After migration a solution to visual studio 2019, the following error occurs when building:

packages\microsoft.intune.mam.remapper.tasks\0.1.4119.2\build\MonoAndroid10\Microsoft.Intune.MAM.Remapper.Tasks.targets(54,5): error MSB4044: The "ResolveAssemblies" task was not given a value for the required parameter "TargetFrameworkVersion".

**Comment by meghandaly** [comment]
Hi @pete-cho, we are aware of this issue and it will be addressed in our next release.

In the meantime, if you add the lines:
```
      ProjectFile="$(MSBuildProjectFullPath)"
      TargetFrameworkVersion="$(TargetFrameworkVersion)"
```
to the `ResolveAssemblies` task in the Microsoft.Intune.MAM.Remapper.Tasks.targets file located at the path reported in the error your project should build properly.

Please be aware that those values will not be compatible with VS2017 so if you want to reopen the solution in VS2017 you will need to remove those values or you will encounter different errors.

**Comment by Totonti** [comment]
Hi, I have change the Task.targets and now the error is :
\packages\microsoft.intune.mam.remapper.tasks\0.1.4119.2\build\MonoAndroid10\Microsoft.Intune.MAM.Remapper.Tasks.targets(94,5): warning : Unable to find method GetMethod on class Microsoft.Intune.Mam.Client.App.WrappedAppReflectionUtils with expected parameters

**Comment by meghandaly** [comment]
Hi @Totonti that appears to be separate from this issue as it is a warning and not an error. Does your solution still not build? If so, can you post the error you are encountering?

**Comment by Totonti** [comment]
Hi, sorry, it's true, now it's compiled correctly.
Now I have a question, for an Android application with MAM-WE
, we will use an application configuration policy: is it necessary to use ADAL and register the application in Azure to obtain the client ID?
In the documentation I have seen that a default ClientID of Intune can be used, is it possible?

**Comment by meghandaly** [comment]
@Totonti all good, I am glad to hear it is compiling correctly. Thank you for checking. 

You have two options for MAM-WE:
1. Register with ADAL and obtain a client ID.
2. Rely on [MAM default enrollment](https://docs.microsoft.com/en-us/intune/app-sdk-android#default-enrollment-optional), which is what the documentation has referred to as the default client ID.

I encourage you to take a look at our [Xamarin sample apps](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps) for additional guidance.

Should you encounter any issues moving forward please submit a new issue so that we can best assist you.

**Comment by Totonti** [comment]
ok, thank you!

**Comment by rbev** [comment]
Given that we need this to build on the Azure Devops Hosted build agent modifying the .targets file from the nuget package isn't really a good option.

Is there any estimated timeframe for the release of this fix?

**Comment by meghandaly** [comment]
Thank y'all for your patience. We have released an updated Remapper package that updates the targets file for VS2019 support. It is available here on GitHub and downloadable via NuGet.

**Comment by daredevil-1982** [comment]
@meghandaly  Can you please share Link to updated package? It seems you have missed adding link to it.

**Comment by meghandaly** [comment]
@daredevil-1982 The updated Remapper package is version 0.1.4428.1.

It can be downloaded from [NuGet](https://www.nuget.org/packages/Microsoft.Intune.MAM.Remapper.Tasks/0.1.4428.1) or from the [Releases page on GitHub](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/releases/tag/5%2F28%2F2019).
