### ISSUE TITLE
Nuget version of Intune SDK for Xamarin 

### ISSUE THREAD

**Issue by msivers** [msintuneappsdk/intune-app-sdk-xamarin#3]
Now that Xamarin Components has been deprecated from Visual Studio, will the Intune SDK for Xamarin be made available via Nuget?

**Comment by Kyle-Reis** [comment]
Hey @msivers, we're working on it!

**Comment by robbo-aj** [comment]
Has any progress been made on this. I've been asked to investigate the current state of Intune with regards to Xamarin apps but have had to say I can't actually install it to check...

**Comment by reutann** [comment]
Hi @robbo-aj, progress is definitely being made. We're hoping to have this and several other changes within the month.

**Comment by robbo-aj** [comment]
Thanks. I'll look forward to trying it out

**Comment by chrisronburns** [comment]
Looking forward to this, thanks guys!

**Comment by reutann** [comment]
@msivers. @robbo-aj, @chrisronburns - you can find the separated DLLs in this repo. Please note that this is currently a public preview that will be released to nuget.org soon so please let us know if you encounter any issues.

**Comment by Kyle-Reis** [comment]
Closing this issue out as we have completed the move to NuGet packages. The documentation at https://docs.microsoft.com/intune/app-sdk-xamarin has also been updated to reflect this move.
