### ISSUE TITLE
Microsoft.Intune.MAM.Xamarin.iOS.8.1.1.2 IntuneMAMConfigurator -i Info.plist -e " exited with code 255. (MSB3073) 

### ISSUE THREAD

**Issue by sureshbabu4** [msintuneappsdk/intune-app-sdk-xamarin#31]
Hi Team,

I got the error like this  packages/Microsoft.Intune.MAM.Xamarin.iOS.8.1.1.2/build/xamarinios10/IntuneMAMConfigurator -i Info.plist -e " exited with code 255. (MSB3073) 

Sample Project I am tried.

Please help me

Thanks in Advance

**Comment by Kyle-Reis** [comment]
Transferred this issue to the correct repo and closing it out. If you're still having trouble here, please reopen.
