### ISSUE TITLE
JNI Error on GetPrimaryUser

### ISSUE THREAD

**Issue by rbev** [msintuneappsdk/intune-app-sdk-xamarin#33]
**Describe the bug:**
When calling intune functionality, either querying policy or using broker authentication through ADAL the application will crash with a JNI error (log attached)

This issue is transient and my assumption is that it's related to some difference in authentication flows when tokens expire since it appears to happen at the same approximate time of day (5-6 hours after first run)

This appears to be similar to https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/5 but the workaround described there does not fix the issue.

**To Reproduce**

The issue is difficult to reproduce and will go away as abruptly as it appeared. It appears to only affect Debug builds.
The particular JNI call doesn't seem to be important and once this error surfaces it seems to persist for an hour or two and then vanish again for a while.

* Full rebuild doesn't seem to help
* Removing and reinstalling the application doesn't clear the error
* A production build will work but when 

**Expected behavior:**

**Screenshots and logs:**

[intune_crash_log.txt](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/files/3404470/intune_crash_log.txt)

**Smartphone (please complete the following information):**
 - Device: Samsung Tab Active 2
 - OS: Android 8.1, Android 9.0

**Intune App SDK Xamarin Bindings (please complete the following information):**
- Versions
```   
    <PackageReference Include="microsoft.csharp" Version="4.5.0" />
    <PackageReference Include="microsoft.identitymodel.clients.activedirectory" Version="5.1.0" />
    <PackageReference Include="microsoft.intune.mam.remapper.tasks" Version="0.1.4428.1" /> 
    <PackageReference Include="microsoft.intune.mam.xamarin.android" Version="3.0.4428.1" />
    <PackageReference Include="Xamarin.Android.Support.Emoji.AppCompat" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v17.Leanback" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.581479" />
    <PackageReference Include="Xamarin.Android.Support.Compat" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.1" />
```
- I have just removed the MAMRemapper library and my application appears to work again, however due to the transient nature of the bug I can't yet confirm this.

**Comment by meghandaly** [comment]
@rbev Can you complete this sentence: "A production build will work but when" ?

**Comment by rbev** [comment]
Sorry, should have read 

"A release build will work and then going back to a debug build it will stop working"


Could this be something to do with the 28.0.0.1 support libs? I notice that the NuGet package targets 27.x

Unfortunately it would be a very major change for me to test that as we moved past xamarin forms 3.5 quite a while ago and there are a lot of other libraries we are using that no longer support that version.

**Comment by rbev** [comment]
Also the final point about removing the mam remapper doesn't seem to actually make a difference, the problem came back.

**Comment by meghandaly** [comment]
@rbev Thank you for that information. 

I would not recommend rolling back your support libs. While the package targets 27.x, our [sample apps](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps) target 28.0.0.1 and function properly. 

I expect the issue is within the bindings themselves so the inclusion of the Remapper would not have an effect on the issue. 

While this is an unfortunate issue, it will not affect release builds. We are working with the Xamarin team to determine why debug builds are impacted in this way.

**Comment by rbev** [comment]
We have updated to the new version (3.0.4500.1) and the issue is still present.

**Comment by rbev** [comment]
This issue is now a month old, has there been any progress on fixing it?

**Comment by rbev** [comment]
Can we please have an update on this bug?

**Comment by meghandaly** [comment]
There is no future development planned for supporting newer Android OS targeting for Xamarin.Android and Xamarin.Forms.

Please [upgrade your existing apps to .NET MAUI](https://learn.microsoft.com/dotnet/maui/migration/?view=net-maui-7.0) and leverage the [Microsoft.Intune.Maui.Essentials.android](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/) NuGet package to enable data protection features and mobile app management.
