### ISSUE TITLE
Get token to use with custom API app uses Intune Xamarin Binding with conditional access

### ISSUE THREAD

**Issue by jlhernandez1388** [msintuneappsdk/intune-app-sdk-xamarin#35]
Hello,

I have been trying for a long time now to retrieve a token with ADAL for .Net. The problem is that our client uses conditional access and prevents login in if it's not from a Microsoft approved app or Intune MAM app. (Please note that this is an app that will be distributed via Intune.)

I'm able to login and register with the Intune SDK successfully. But the Intune SDK doesn't provide a token so we can use it with our custom API. 

My understanding is that I can use broker to share a keychain between Intune SDK and ADAL for .Net. If I try to acquire a token silently after login in with the Intune SDK, it doesn't find anything in the cache. If i use the acquiretokenasync it asks for credentials and then it throws the same error "You cannot access the resource from this browser on your device."

Steps I have taken:

- I have added the keychain-access-groups
- Added scheme to LSApplicationQueriesSchemes
- Added IntuneMAMSettings 
- Added URL Types
- Added URI Redirects
- etc.

I have been following this references: 

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS#brokered-authentication-for-android

https://github.com/AzureAD/azure-activedirectory-library-for-objc#brokered-authentication

https://docs.microsoft.com/en-us/intune/app-sdk-ios

https://docs.microsoft.com/en-us/intune/app-sdk-xamarin

Please any help will be appreciated.

Thanks!

**Comment by Kyle-Reis** [comment]
Hey @jlhernandez1388, do you still need help with this?

**Comment by Kyle-Reis** [comment]
@jlhernandez1388, checking in again if you need help with this issue.

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. If you're still having problems, feel free to reopen!
