### ISSUE TITLE
Package Microsoft.Intune.MAM.Xamarin.Android 3.0.4635.1 referencing failed

### ISSUE THREAD

**Issue by dm-CaT** [msintuneappsdk/intune-app-sdk-xamarin#36]
**Describe the bug:**
I cannot reference "Microsoft.Intune.MAM.Xamarin.Android" 3.0.4635.1

**To Reproduce**
1. Create new Xamarin Forms Project
2. Select Shell template
3. Update the NuGet package Xamarin.Forms to the '4.4.0.991477' version for the whole solution.
4. Try to install Microsoft.Intune.MAM.Xamarin.Android '3.0.4635.1' package in the Android project.
5. Install failed (see error messages below)

**Expected behavior:**
The package is installed.

**Screenshots and logs:**
Two error messages are generated.
1. Package restore failed. Rolling back package changes for 'XamFormsIntune.Android'.
2. NU1107	Version conflict detected for Xamarin.Android.Support.v7.RecyclerView. Install/reference Xamarin.Android.Support.v7.RecyclerView 28.0.0.3 directly to project XamFormsIntune.Android to resolve this issue. 
 XamFormsIntune.Android -> Xamarin.Forms 4.4.0.991477 -> Xamarin.Android.Support.Design 28.0.0.3 -> Xamarin.Android.Support.v7.RecyclerView (= 28.0.0.3) 
 XamFormsIntune.Android -> Microsoft.Intune.MAM.Xamarin.Android 3.0.4635.1 -> Xamarin.Android.Support.v17.Leanback 28.0.0.1 -> Xamarin.Android.Support.v7.RecyclerView (= 28.0.0.1).	XamFormsIntune.Android	D:\Xam.Intune\XamFormsIntune\XamFormsIntune\XamFormsIntune.Android\XamFormsIntune.Android.csproj
	

**Smartphone (please complete the following information):**
N/A

**Intune App SDK Xamarin Bindings (please complete the following information):**
- What version of the Xamarin Bindings are you using? Are you using the latest version?
N/A

**Additional context:**
N/A

**Comment by meghandaly** [comment]
This should be resolvable by directly importing the support library NuGet packages to your project as the error suggests.

The Microsoft.Intune.MAM.Xamarin.Android package is compatible with the 28.0.0.3 support packages.

**Comment by dm-CaT** [comment]
@meghandaly, thanks.
Finally, I've got Microsoft.Intune.MAM.Xamarin.Android installed. 
Next NuGet packages should be referenced directly.

Xamarin.Android.Support.v7.RecyclerView 28.0.0.3
Xamarin.Android.Support.Core.UI 28.0.0.3
Xamarin.Android.Support.Fragment 28.0.0.3
Xamarin.Android.Support.Media.Compat 28.0.0.3

**Comment by meghandaly** [comment]
@dm-CaT I am happy to hear that. We will look into bumping the support library dependency in the next release.
