### ISSUE TITLE
New Xamarin Forms Android project using Remapper throws "You MUST call Xamarin.Forms.Init(); prior to using it".

### ISSUE THREAD

**Issue by Knots23** [msintuneappsdk/intune-app-sdk-xamarin#38]
**Describe the bug:**
I just created a new Xamarin Forms project using:
- Visual Studio 16.5.3
- Xamarin Android 10.2.0.100
- Xamarin Forms 4.5.0.396
- Microsoft Intune MAM Remapper Tasks 0.1.4635.1

As my actual project, I've added a splash screen as can be seen in the code below. This screen waits for 2 seconds, then starts the actual app.

When running this sample, the build succeeds, but when it starts it immediately throws the exception:
`You MUST call Xamarin.Forms.Init(); prior to using it`
even though this init can be seen in the OnMAMCreate of the splash screen.

Removing the splash screen completely and placing the Init back in the OnMAMCreate of the MainActivity results in a starting app, but one just showing a white screen.

This problem occurred after updating to Visual Studio 16.5.3. A colleague confirmed it also occurs on 16.5.2. I don't know the exact version of Visual Studio I had before this update, but it was in the 16.3.x range.

**To Reproduce**
1. Create a new Xamarin Forms project.
2. Opt for the MasterDetail view.
3. Select Android only; no iOS or UWP needed.
4. Create the project.
5. Open the NuGet manager for the Android project.
6. Update Xamarin Forms to 4.5.0.396
7. Add the following packages to the Android project (or the Intune package will not install)
   - Xamarin.Android.Support.Emoji.AppCompat 28.0.0.3
   - Xamarin.Android.Support.v17.Leanback 28.0.0.3
8. Add the packages only on the Android project:
   - Microsoft.Intune.MAM.Xamarin.Android 3.0.4635.1
   - Microsoft.Intune.MAM.Remapper.Tasks 0.1.4635.1
9. Change the MainActivity.cs code to the following:
```
[Activity(Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class SplashScreen : Xamarin.Forms.Platform.Android.FormsApplicationActivity
    {
        protected override void OnMAMCreate(Bundle savedInstanceState)
        {
            base.OnMAMCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            Xamarin.Forms.Forms.Init(this, savedInstanceState);
        }

        protected override void OnMAMResume()
        {
            base.OnMAMResume();

            var handler = new Handler();
            handler.PostDelayed(() =>
            {
                var app = new Intent(Application.Context, typeof(MainActivity));

                if (Intent != null)
                    app.PutExtras(Intent);

                StartActivity(app);
                Finish();
                OverridePendingTransition(0, 0);
            }, 2000);
        }
    }
    //*/

    [Activity(Label = "App2", Theme = "@style/MainTheme", ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnMAMCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnMAMCreate(savedInstanceState);

            // Enable this, disable the above method and put the "MainLauncher = true" in the activity attribute of this method
            // to see the result without a splash screen.

            //Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            //Xamarin.Forms.Forms.Init(this, savedInstanceState);

            LoadApplication(new App());
        }
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }
```
10. Delete the bin/obj folder for the Android project.
11. Clean the solution.
12. Run the solution (Debug | Any CPU) on a device. (I'm using a Samsung Galaxy S8)

**Expected behavior:**
The project starts normally, i.e. the OnMAMCreate method is executed and not skipped for some reason. This should result in the Xamarin.Forms.Init(); method being called.

**Smartphone (please complete the following information):**
 - Samsung Galaxy S8 | Android 9
 - LG V30 | Lineage OS 16.0

**Intune App SDK Xamarin Bindings (please complete the following information):**
- What version of the Xamarin Bindings are you using? Are you using the latest version?
   - Microsoft.Intune.MAM.Xamarin.Android 3.0.4635.1
   - Microsoft.Intune.MAM.Remapper.Tasks 0.1.4635.1
- For errors during build, does the app build without Intune SDK Xamarin Bindings integration?
   - n.a.
- For errors post build, does the app launch without being Intune SDK Bindings integrated?
   - Yes, when skipping steps 5 through 11, the project builds and runs normally.
- Who is the customer?
   - Our customers. We cannot provide updates or bugfixes for the actual app, as we cannot even test them locally.
- Do you see a trend with it only being reproduced on a specific device?
   - No.

**Comment by Knots23** [comment]
It's been twelve days since I've posted this issue and nobody responded... Can anybody help me out here as I cannot debug/test Android apps at all?

**Comment by sowmini** [comment]
@Knots23 : We are facing the same issue with the app showing a black white screen and are unable to debug the app in spite of configuring the app to debug(per the docs).. Were you able to resolve this issue? Any insights on this would be greatly appreciated.

**Comment by Knots23** [comment]
@sowmini : unfortunately not. We ditched Intune as there was no response at all. Being able to debug has a higher priority than having Intune in our app...

**Comment by sowmini** [comment]
@Knots23 thanks for your response. We are probably going to do the same and try the Intune wrapping tool and see how that works.

**Comment by meghandaly** [comment]
Please refer to Issue #42 . We are aware of the issue with debugging and will be keeping that issue for tracking purposes.

Furthermore, we are actively reevaluating our Xamarin support and are working to better address issues in the future and we thank you for your patience.
