### ISSUE TITLE
Intune SDK for IOS v. 12.4.0 

### ISSUE THREAD

**Issue by Totonti** [msintuneappsdk/intune-app-sdk-xamarin#39]
Hi,
I just wanted to ask when the library will be compiled with the latest version of Intune SDK for IOS v. 12.4.0 to avoid UIWebView problem.
Thank you

**Comment by Kyle-Reis** [comment]
Hey @Totonti, we're working on getting the bindings updated now. Thanks!

**Comment by Totonti** [comment]
Thanks 😊

**Comment by Kyle-Reis** [comment]
Hi @Totonti, version 12.4.0 of the Xamarin.iOS bindings is now available: https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.iOS/latest
