### ISSUE TITLE
Xamarin forms + msal + Intune sdk 

### ISSUE THREAD

**Issue by viveknegi51288** [msintuneappsdk/intune-app-sdk-xamarin#41]
Can you please provide sample app for xamarin forms + intune sdk.

I have created an application in xamarin forms with MSAL library, Where i am able to get mfa token , now I need to integrate intune sdk to this application, 

I followed all the steps but my application get stuck at splash screen(my own splash screen)

I need your help to provide steps , what Need to do after login successfully and got the token,

then how to check intunes policy ? Currenly I am checking on IOS.

Please help

**Comment by viveknegi51288** [comment]
@msintuneappsdk @oydang @Kyle-Reis @reutann

**Comment by Kyle-Reis** [comment]
Hey @viveknegi51288, we don't have a sample app for Xamarin forms specifically, but the integration process should be the same as any Xamarin.iOS app. You can reference [this sample](https://github.com/msintuneappsdk/sample-intune-xamarin-ios). That sample calls LoginAndEnrollAccount, but if your app is doing it's own auth, you'll want to call RegisterAndEnrollAccount after successfully acquiring a token from MSAL. 

Questions:
 1.) Have you followed [these steps](https://docs.microsoft.com/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional) to give your app access to the Intune app protection service? 
2.) Have you configured ADALClientId and ADALRedirectUri in the app's Info.plist as mentioned [here](https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#configure-adalmsal-settings-for-the-intune-app-sdk)?

**Comment by viveknegi51288** [comment]
@Kyle-Reis  Thank you for the reply, I able to embed intunes ios sdk with MSAL and able to register the user in intunes but for android I am not getting any help from anywhere as in official doc also only ADAL with Android intune sdk explained. Can you help how to integrate MSAL with ANdroid intune sdk.

**Comment by Kyle-Reis** [comment]
@cofitz1 or @meghandaly, could you help with the above? Thanks.

**Comment by viveknegi51288** [comment]
@cofitz1  and @meghandaly Please help

**Comment by meghandaly** [comment]
Apologies for the delay.

We are updating our MSAL documentation and our sample apps to help users connect their MSAL and MAM integrations. I will post here when both are available.

Questions: 
1. Without MAM are you able to successful log ininto your Android app?
2. Has your app implemented a `IMAMServiceAuthenticationCallback` for acquiring the token for MAM?

We are actively reevaluating our Xamarin support and are working to better address issues in the future and we thank you for your patience.

**Comment by viveknegi51288** [comment]
@meghandaly  Not an issue... I have implemented successfully (Xamarin forms + msal + Intune sdk) . Closing the ticket
