### ISSUE TITLE
Cannot Deploy App in Debug Mode with Android MAM Integration

### ISSUE THREAD

**Issue by Totonti** [msintuneappsdk/intune-app-sdk-xamarin#42]
**Describe the bug:**
I can't debug the project. I have  [Application(Debuggable = false)] but it doesn't work.
I'm using the DefaultEnrollment in Android Xamarin forms project.
<meta-data android:name="com.microsoft.intune.mam.DefaultMAMServiceEnrollment" android:value="true" />

I notice that in background the android project is always compiling.  is it normal? see image

Visual Studio version: see image.

**To Reproduce**
try to debug the project

**Expected behavior:**
Debug the project

**Screenshots and logs:**
![image](https://user-images.githubusercontent.com/46727161/86906472-e2b0d300-c113-11ea-97a6-411e4d3af5a8.png)
![image](https://user-images.githubusercontent.com/46727161/86907237-06c0e400-c115-11ea-9658-282f6d744f3d.png)

- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
"No se pudo conectar el depurador. Puede ver más detalles en la salida de Xamarin Diagnostic y la excepción completa en los registros."
![image](https://user-images.githubusercontent.com/46727161/86938465-beb7b680-c140-11ea-9526-6e9602d1c4c5.png)

**Smartphone (please complete the following information):**
 - Device: tablet Samsung Tab A 2016
 - OS: android 8.1.0

**Intune App SDK Xamarin Bindings (please complete the following information):**
- What version of the Xamarin Bindings are you using? Are you using the latest version?
Latest version
- For errors during build, does the app build without Intune SDK Xamarin Bindings integration?
n.a
- For errors post build, does the app launch without being Intune SDK Bindings integrated?
YES
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?
NO
**Additional context:**

**Comment by meghandaly** [comment]
We are aware of this issue and apologize for delay in response. 

While we don't have a fix in hand, we do have the following workaround:

1. Deploy the app in Release mode.
2. Navigate to the `mamRemapperOutput` in the build `obj` folder. i.e `E:\IntuneSDKXamarinForms\IntuneSDKXamarinForms\IntuneSDKXamarinForms\IntuneSDKXamarinForms.Android\obj\Release\90\mamRemapperOutput`
3. Copy the `Xamarin.Forms.Platform.Android.dll` file.
4. Navigate to the Forms NuGet cache location and replace the internal `Xamarin.Forms.Platform.dll` file with the copied one. i.e. `D:\NuGetPackages\xamarin.forms\4.8.0.1451\lib\MonoAndroid90`
5. Remove the `Remapper` from the application.
6. Build and deploy in Debug mode.

We are actively reevaluating our Xamarin support and are working to better address issues in the future and we thank you for your patience.

**Comment by rrajarap** [comment]
Hi, is there any update on this issue?

**Comment by rrajarap** [comment]
Hi, is there any update on this issue?

**Comment by meghandaly** [comment]
There is no future development planned for supporting newer Android OS targeting for Xamarin.Android and Xamarin.Forms.

For apps that target Android 10.0+, please [upgrade your existing apps to .NET MAUI](https://learn.microsoft.com/dotnet/maui/migration/?view=net-maui-7.0) and leverage the [Microsoft.Intune.Maui.Essentials.android](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/) NuGet package to enable data protection features and mobile app management.
