### ISSUE TITLE
IntuneMAMConfigurator fails on remote Windows build

### ISSUE THREAD

**Issue by ldrtzstmmns** [msintuneappsdk/intune-app-sdk-xamarin#46]
**Describe the bug:**
When trying to build an iOS application with the Intune SDK installed using a remote macOS computer, it will fail with the following message:
`The command "chmod +x IntuneMAMConfigurator" exited with code 255.`

This happens with the Entitlements.plist file properly configured and attached to the csproj.

This does not happen if compiling directly in macOS.

**To Reproduce**
1. Add the Intune Xamarin iOS SDK to a Xamarin iOS project.
2. Do the corresponding SDK setup.
3. Connect to a macOS from a Windows machine with Visual Studio.
4. Try to build iOS project, it will fail.

**Expected behavior:**
Should build correctly just like when building directly in macOS.

**Screenshots and logs:**
```
1>  chmod +x IntuneMAMConfigurator
1>  /var/folders/bc/s06vgm1n5pb7wtwhz1j0p8x40000gn/T/tmp4d39c0770f5f47f99d838af884410371.exec.cmd: line 1: setlocal: command not found
1>  /var/folders/bc/s06vgm1n5pb7wtwhz1j0p8x40000gn/T/tmp4d39c0770f5f47f99d838af884410371.exec.cmd: line 5: exit: %errorlevel%: numeric argument required
1> %UserProfile%\.nuget\packages\microsoft.intune.mam.xamarin.ios\14.1.3\build\xamarinios10\Microsoft.Intune.MAM.Xamarin.iOS.targets(23,5): error MSB3073: The command "chmod +x IntuneMAMConfigurator" exited with code 255.
```

**Intune App SDK Xamarin Bindings (please complete the following information):**
- What version of the Xamarin Bindings are you using? Are you using the latest version? 14.1.3, yes.
- For errors during build, does the app build without Intune SDK Xamarin Bindings integration? Yes.
- For errors post build, does the app launch without being Intune SDK Bindings integrated? N/A.
- Who is the customer? Stemmons Enterprise, LLC.
- Do you see a trend with it only being reproduced on a specific device? N/A.

**Comment by Kyle-Reis** [comment]
Hi @ldrtzstmmns, which version of VS/Xamarin are you building with?
