### ISSUE TITLE
Problem upgrading to Microsoft.Intune.MAM.Xamarin.iOS.14.7.0

### ISSUE THREAD

**Issue by miguelweiss** [msintuneappsdk/intune-app-sdk-xamarin#50]
I'm working in a Xamarin Forms project that is currently using the Microsoft.Intune.MAM.Xamarin.iOS.14.3.5 for an iOS mobile application.  We are looking forward to upgrade to the latest Microsoft.Intune.MAM.Xamarin.iOS.14.7.0 version.

When we update the Nuget package to reference the new 14.7.0 and run the build we are getting the following 17 error messages:

1. MTOUCH: Error MT5214: Native linking failed, undefined symbol: _IntuneMAMAllowedAccountsDidChangeNotification. This symbol was referenced by the managed member Microsoft.Intune.MAM.IntuneMAMEnrollmentManager.AllowedAccountsDidChangeNotification. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214).
2. MTOUCH: Error MT5214: Native linking failed, undefined symbol: _IntuneMAMAppConfigDidChangeNotification. This symbol was referenced by the managed member Microsoft.Intune.MAM.IntuneMAMAppConfigManager.AppConfigDidChangeNotification. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214).
3. MTOUCH: Error MT5214: Native linking failed, undefined symbol: _IntuneMAMDataProtectionDidChangeNotification. This symbol was referenced by the managed member Microsoft.Intune.MAM.IntuneMAMDataProtectionManager.DataProtectionDidChangeNotification. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214). 
4. MTOUCH: Error MT5214: Native linking failed, undefined symbol: _IntuneMAMPolicyDidChangeNotification. This symbol was referenced by the managed member Microsoft.Intune.MAM.IntuneMAMPolicyManager.PolicyDidChangeNotification. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214) 
5. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMAppConfigManager. The symbol '_OBJC_CLASS_$_IntuneMAMAppConfigManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
6. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMCertificatePinningManager. The symbol '_OBJC_CLASS_$_IntuneMAMCertificatePinningManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
7. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMComplianceManager. The symbol '_OBJC_CLASS_$_IntuneMAMComplianceManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
8. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMDataProtectionManager. The symbol '_OBJC_CLASS_$_IntuneMAMDataProtectionManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
9. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMDiagnosticConsole. The symbol '_OBJC_CLASS_$_IntuneMAMDiagnosticConsole' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
10. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMEnrollmentManager. The symbol '_OBJC_CLASS_$_IntuneMAMEnrollmentManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
11. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMEnrollmentStatus. The symbol '_OBJC_CLASS_$_IntuneMAMEnrollmentStatus' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
12. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMFile. The symbol '_OBJC_CLASS_$_IntuneMAMFile' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
13. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMFileProtectionManager. The symbol '_OBJC_CLASS_$_IntuneMAMFileProtectionManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
14. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMPolicyManager. The symbol '_OBJC_CLASS_$_IntuneMAMPolicyManager' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
15. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMSettings. The symbol '_OBJC_CLASS_$_IntuneMAMSettings' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
16. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMUIHelper. The symbol '_OBJC_CLASS_$_IntuneMAMUIHelper' could not be found in any of the libraries or frameworks linked with your application. (MT5211).
17. MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: IntuneMAMVersionInfo. The symbol '_OBJC_CLASS_$_IntuneMAMVersionInfo' could not be found in any of the libraries or frameworks linked with your application. (MT5211).

Any idea what the problem can be?  
Are we missing to reference some specific package?  Which one?

The interesting thing is that when we rollback to the Microsoft.Intune.MAM.Xamarin.iOS.14.3.5 version we are not getting any of these build errors.

Thank you very much for all your help.

**Comment by darosal** [comment]
Thank you for reaching out and bringing this to our attention! Could I get more details about your build machine setup so that I can attempt to reproduce this locally? Are you building on Windows vs OSX? Are you building for simulator or device?

**Comment by miguelweiss** [comment]
I'm currently working on macOS Bug Sur version 11.6.
Using Visual Studio Enterprise 2019 for Mac with Xamarin.iOS Version: 14.20.0.24.
Building for a physical device that is running the latest iOS 15 beta.

Thank you very much

**Comment by darosal** [comment]
Great, thanks! One last thing just to confirm, do you still get all the errors after doing a "Build > Clean All" within Visual Studio?

**Comment by miguelweiss** [comment]
Yes.  I still get the same error messages after doing a "Build > Clean All" and then a "Build > Build All" in visual studio.  
Any ideas what I could be missing or doing wrong?

**Comment by darosal** [comment]
We recently made a change to how our bindings link to the MAM SDK. It's possible that introduced the issue you are seeing. We will be reverting some of this change very soon to fulfill nuget.org upload requirements so hopefully that will also resolve your issue. But since we want to make the change again in the longterm, I think it's still worth investigating this issue a bit more.

How is your app consuming the binding project in Visual Studio? Is it updating to 14.7.1 through Visual Studio UI (using a local package source) or by replacing the file in Finder?

**Comment by miguelweiss** [comment]
As you mentioned the new package is not available in nuget.org, therefore we've downloaded the "Microsoft.Intune.MAM.Xamarin.iOS.14.7.0.nupkg" from the GitHub repository.  Then we use Visual Studio to consume this package from a local source.  "Visual Studio > preferences > Nuget > Sources".

The reason why we wished to use the 14.7.0 version is because iOS mobile applications using the "Microsoft.Intune.MAM.Xamarin.iOS 14.3.5" are crashing when running in the new iOS 15 Beta.  
Our hope is that with this new "Microsoft.Intune.MAM.Xamarin.iOS 14.7.0" package the applications will not crash in iOS 15.

**Comment by darosal** [comment]
Could you try the new 14.7.1 version and see if that solves the issue? It is up both here on GitHub and on nuget.org.

**Comment by darosal** [comment]
I do also want to note that the crash was caused by an issue in the ADAL version we were using. As part of 14.7.0 and 14.7.1 releases, we have switched over to MSAL. Please make sure to update the redirect URI in the app's Info.plist to an MSAL accepted format if you haven't already.

**Comment by miguelweiss** [comment]
Awesome, switching over to version 14.7.1 made the trick.  I no longer see the build errors.

Thank you very much for all your help.

**Comment by darosal** [comment]
Thats great to hear! Please feel free to reach out again if any other issues pop up.
