### ISSUE TITLE
Microsoft Intune App SDK integrate with Xamarin Forms along with MSAL  

### ISSUE THREAD

**Issue by PavanRaghamwa** [msintuneappsdk/intune-app-sdk-xamarin#55]
Can you please provide sample app for xamarin forms + MSAL + InTune sdk.

I have created an application in xamarin forms with MSAL library and now I need to integrate intune sdk to this application.

Does this SDK supports latest Xamarin Forms(v5.0 or Greater) , Android 13 and iOS 15 or 16 version?

Samples provided in documentation are not able to run. (Android Sample Min Target Version is v4.0 and Max Target Version is v9.0).

Currently Using Visual Studio For MAC 2022 (v 17.3.4).

Please suggest steps for further development.

**Comment by abasore** [comment]
@PavanRaghamwa For the iOS side, we do support iOS 15 + iOS 16. We don't have a xamarin forms example app yet. In case you didn't see this, we do have this example xamarin app app: https://github.com/msintuneappsdk/sample-intune-xamarin-ios

This doc also mentions special considerations when using xamarin forms: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin#enabling-intune-app-protection-policies-in-your-android-mobile-app
