### ISSUE TITLE
Is there a plan to support MAUI besides Xamarin?

### ISSUE THREAD

**Issue by leungkimming** [msintuneappsdk/intune-app-sdk-xamarin#58]
Xamarin support will end by May 2024. Without intune app sdk for MAUI, we cannot migrate from Xamarin to MAUI. Please seriously consider.

**Comment by c-demello** [comment]
Intune support for MAUI is currently in development and will be available before Xamarin support ends  - [[Microsoft Intune App SDK Xamarin Bindings | Microsoft Learn](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-xamarin)].

**Comment by bannus** [comment]
@leungkimming, we have release a [beta version of our Android support for MAUI](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/9.5.2-beta). Please try it out and let us know if you have any feedback.

**Comment by leungkimming** [comment]
Thank you. Do you have a plan for IOS support?

**Comment by gustavoja** [comment]
Hello @bannus I tried the beta version and it is working ok on my test project. Is there any estimated date for an stable release?
I also reported this issue with it
https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/61#issuecomment-1683539273

**Comment by bannus** [comment]
Hi @gustavoja, no estimated date to share currently. Thanks for reporting that issue, it will be fixed in an upcoming release.

**Comment by mafrank1** [comment]
@bannus Xamarin support is slowly coming to an end. Currently there is no iOS Intune SDK for MAUI and the Android Intune SDK is still in beta. For us it is getting time critical to get the new Intune SDKs for MAUI. When can we expect the fixed releases?

Thanks,
Markus
