### ISSUE TITLE
Enrollment failed: SDK could not access the user AAD token

### ISSUE THREAD

**Issue by leoslima13** [msintuneappsdk/intune-app-sdk-xamarin#60]
Our app use MSAL SDK for authentication and then use `RegisterAndEnrollAccount` to enroll with Intune. But when calling this method i'm getting:

`The operation failed because the SDK could not access the user\'s AAD token.  The application should prompt the user for credentials to refresh the user\'s AAD token.`

Note: Azure AD app is enabled with option Accounts in any organizational directory.... Azure AD app also has this API permission DeviceManagementManagedApps.ReadWrite

And I can't even use `LoginAndEnrollAccount` because i'm getting this error `The operation couldn't be completed. (MSALErrorDomain error -50000.)`, So I believe is something wrong when you want to have `MSAL + Intune`, because if I remove all MSAL configurations, the `LoginAndEnrollAccount` works like a charm, but I need to use the MSAL to acquire the token after the authentication

BTW all the configurations are set on info.plist:

`<key>CFBundleURLTypes</key>

	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msauth.{MY_BUNDLE_IDENTIFIER}</string>
				<string>msauth.{MY_BUNDLE_IDENTIFIER}-mam</string>
				<string>msauth.com.microsoft.intunemam</string>
				<string>msauth.{MY_BUNDLE_IDENTIFIER}://auth</string>
				<string>msauth.{MY_BUNDLE_IDENTIFIER}://auth-intunemam</string> **THIS ONE WAS ADDED AUTOMATICALLY**
			</array>
		</dict>
	</array>`

`<key>IntuneMAMSettings</key>

	<dict>
		<key>ADALAuthority</key>
		<string>https://login.microsoftonline.com/{MY_TENANT_ID}</string>
		<key>ADALClientId</key>
		<string>{MY_CLIENT_ID}</string>
		<key>ADALRedirectUri</key>
		<string>msauth.{MY_BUNDLE_IDENTIFIER}://auth</string>
	</dict>`

`<key>LSApplicationQueriesSchemes</key>

	<array>
		<string>scmx</string>
		<string>smsec</string>
		<string>microsoft-edge-http</string>
		<string>microsoft-edge-http-intunemam</string>
		<string>lookoutwork-ase</string>
		<string>mvisionmobile</string>
		<string>skycure</string>
		<string>companyportal</string>
		<string>lacoonsecurity</string>
		<string>msauthv2</string>
		<string>wandera</string>
		<string>betteractiveshield</string>
		<string>msauthv3</string>
		<string>microsoft-edge-https</string>
		<string>microsoft-edge-https-intunemam</string>
		<string>zips</string>
		<string>ms-outlook</string>
		<string>ms-outlook-intunemam</string>
		<string>smart-ns</string>
		<string>https-intunemam</string>
		<string>http-intunemam</string>
	</array>`

Device:

iOS 15.5 / 16.0 / 16.2

Microsoft.Identity.Client: 4.53.0
Microsoft.Intune.MAM.Xamarin.iOS: 17.4.0

**Comment by Kyle-Reis** [comment]
Hi @leoslima13 - Have the keychain access groups mentioned in step 4 [here](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app) been added to your app's entitlements? Also, just want to confirm that the redirect URI (msauth.{MY_BUNDLE_IDENTIFIER}://auth) has been added to the app registration which maps to your client ID?

**Comment by leoslima13** [comment]
Hey @Kyle-Reis thank you for your response, and yes, all the keychain is configured correctly on Entitlement.plist:

```
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>keychain-access-groups</key>
        <array>
            <string>$(AppIdentifierPrefix){MY_BUNDLE_IDENTIFIER}</string>
            <string>$(AppIdentifierPrefix)com.microsoft.intune.mam</string>
            <string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
        </array>
    </dict>
</plist>
```

And also my bundle id is configured correctly on Azure Portal for redirect URI:
![Screenshot 2023-05-09 at 19 41 57](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/48806623/16fbb78f-5464-42e6-936a-8ed40e43290d)

**Comment by Kyle-Reis** [comment]
Hi @leoslima13 - Could you call IntuneMAMDiagnosticConsole.DisplayDiagnosticConsole() to display the Intune diagnostic console in the app, then upload the logs to Microsoft and share the reference ID with me here?

**Comment by leoslima13** [comment]
Hi @Kyle-Reis both logs was shared with MS (**C55EA5**/**B8C667**)
Hope that you can help me with this

**Comment by Kyle-Reis** [comment]
Hi @leoslima13, could you verify that the Entitlements.plist file is specified for the "Custom Entitlements" field in the iOS Bundle Signing options? Be sure to change the "Configuration" and  "Platform" options at the top to match the config/platform you are building. Here is a sample  image for reference:

<img width="914" alt="image" src="https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/7443106/744681cb-e519-4b92-b5c0-cbe882631934">

**Comment by Kyle-Reis** [comment]
Also, when calling registerAndEnrollAccount, are you passing in the user's UPN for a value?

**Comment by leoslima13** [comment]
Hey @Kyle-Reis thank you for your quick response, yeah as you can see on my screenshot the `Entitlement.plist` is specified correctly on csproj:

![Screenshot 2023-05-12 at 17 35 29](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/48806623/70c402fe-0d52-468d-898c-57bfdabd3e40)

And yeah, i'm passing the UPN (AuthenticationResult.Account.UserName):

![Screenshot 2023-05-12 at 17 38 42](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/48806623/d4ab9ff1-c297-42e8-a459-67301b0aaca2)

**Comment by Kyle-Reis** [comment]
Thanks @leoslima13 - Which version of .Net MSAL is your app consuming? Is your app passing in the .WithIosKeychainSecurityGroup option to PublicClientApplicationBuilder?

**Comment by leoslima13** [comment]
@Kyle-Reis 
MSAL .net version: `Microsoft.Identity.Client: 4.53.0`
And yes MSAL is configured .`WithIosKeychainSecurityGroup` option to PCABuilder as you can see below:

![Screenshot 2023-05-12 at 18 03 42](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/48806623/2acc2fc3-df8f-4b94-bc68-e9cea278d1e0)

**Comment by Kyle-Reis** [comment]
Ah, could you omit that? By default both .Net and Objective-C MSAL will use the com.microsoft.adalcache keychain group, which should allow Intune's registerAndEnrollAccount to start picking up on tokens cached by .Net MSAL.

Alternatively, you could use the ADALCacheKeychainGroupOverride Intune setting listed here to configure Intune to use the same access group you've set for .Net MSAL, but I think it would be best to have all the auth data stored in a siloed keychain group.

**Comment by leoslima13** [comment]
@Kyle-Reis same error even without the `.WithIosKeychainSecurityGroup`

![Screenshot 2023-05-12 at 18 43 51](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/48806623/1f4f0960-8630-42bf-b1ce-528f6a78417f)

**Comment by leoslima13** [comment]
Hey @Kyle-Reis do you know if we can change something else? 
The result was the same after following your requests

**Comment by Kyle-Reis** [comment]
Hi @leoslima13 - When making the initial AcquireTokenInteractively call with .Net MSAL, is your app [using an embedded webview](https://learn.microsoft.com/azure/active-directory/develop/msal-net-web-browsers#developer-options)? If not can you add .WithUseEmbeddedWebView() to the call and pass in a value of true? On iOS, this will result in the use of WKWebView for the authentication, which is [required by Intune](https://learn.microsoft.com/mem/intune/developer/app-sdk-ios#special-considerations-when-using-msal-for-app-initiated-authentication).

**Comment by leoslima13** [comment]
Hey @Kyle-Reis yes, i'm using `.WithUseEmbeddedWebView(true)` on first interaction:

![Screenshot 2023-05-16 at 15 55 20](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/48806623/4d5d1df0-1549-4f4e-a164-b414098d611b)

**Comment by Kyle-Reis** [comment]
Thanks for confirming, @leoslima13. When granting access to the Intune MAM service for the app registration in the Azure Portal, was the "Grant admin consent for [Tenant Name]" button shown below selected? 

![image](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/assets/7443106/6f6e8571-a14a-410d-8236-1b5f7d974cb9)

**Comment by leoslima13** [comment]
Hey @Kyle-Reis how can I add this Microsoft Mobile Application Manager on Azure Portal? I didn't found it here

**Comment by Kyle-Reis** [comment]
HI @leoslima13, see the instructions here: https://learn.microsoft.com/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional

**Comment by leoslima13** [comment]
Hi @Kyle-Reis thank you, we changed this configuration on Azure Portal, but we are still getting the same error after that:

`
Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent.}
`

**Comment by Kyle-Reis** [comment]
Hi @leoslima13 - Can you upload a new set of logs after reproducing the issue with all of the changes we've discussed here applied?

**Comment by leoslima13** [comment]
@Kyle-Reis sure, just shared with ID: `C23B31`

**Comment by Kyle-Reis** [comment]
Hi @leoslima13 Could you check to see if loginAndEnrollAccount works now? This is not a permanent change that I'm suggesting, but just want to see if all the MSAL configuration issues have been addressed, and if we might just be dealing with an issue with accessing the token acquired by the app for silent enrollment. If the loginAndEnrollAccount results in an error, please collect logs and and provide the reference ID for that case.

**Comment by leoslima13** [comment]
Hey @Kyle-Reis actually the `loginAndEnrollAccount` always worked alone, but the issue with this for me it's because I can't get the access token after login works
But to `LoginAndEnrollAccount` works, I need to remove the `ADALClientId` from `info.plist` file

**Comment by Kyle-Reis** [comment]
Understood, can we try now with the ADAL settings specified in the Info.plist file? If everything is configured correctly and admin consent has been provided on the backend for MAM service, interactive auth should work. Just want to make sure we've addressed any AAD config issues before diving into why the silent enrollment attempt is failing.

**Comment by leoslima13** [comment]
@Kyle-Reis it didn't worked, when I called `LoginAndEnrollAccount`, the application asks for open the `Authenticator` App, after I grant the permission to open the application, it returns a **-50000 error.**

I just sent the logs for Microsoft again its: `519FB4`

**Comment by leoslima13** [comment]
Hey @Kyle-Reis sorry for the other response, I was forgot to replace the **tenantId** and **clientID** on info.plist, it worked fine `LoginAndEnrollAccount` with all configurations set up

**Comment by Kyle-Reis** [comment]
@leoslima13 - Great! Now that we're sure the config is all good, we just need to figure out the silent enrollment issue. Was the clientID/authority URI also misconfigured when you last tested that? If so can we retry with the correct values set in Info.plist? You should do this on a cleanly reset device/simulator to be sure that the token obtained from the loginAndEnroll test does not get picked up for silent enrollment

**Comment by Kyle-Reis** [comment]
@leoslima13 - Uninstalling and re-installing the application won't clear the AAD token cache from the keychain. To be certain the scenario will work for a user on first install, I would try testing on a clean device or simulator

**Comment by leoslima13** [comment]
Hey @Kyle-Reis good news, I tried on a new device and simulator and both worked as expected! So I tried to use the silent enrollment and it also worked, thank you very much for your help on it!

Now I have another question for you, I can't use this sdk on my `Android` version of application, because the sdk only supports **Android 4.4 and lower**, do you guys have any plans to update it?
I noticed that already have a beta version for `MAUI`, but the package is only for **Android**, so **I cannot migrate** to `MAUI` because the sdk **does not** supports `iOS`, and cannot implement on `Android` because the sdk only supports old versions.

Do you have any ideas/tips to me, on how to implement this on both platforms, without having two solutions (Xamarin for iOS and MAUI for Android)?

**Comment by Kyle-Reis** [comment]
Hi @leoslima13 - Just wanted to double check that silent enrollment is working for you on a cleanly reset device or simulator which was reset using the "Erase all content and settings" option to wipe the keychain? From your last reply it sounded like you may have tested the registerAndEnroll case after testing loginAndEnroll. If so it's possible that the token acquired in the first test could have been used for the silent enrollment in the 2nd test. Does registerAndEnroll also work on a clean device where only tokens that have been acquired were through your apps's .Net MSAL acquireToken call?

**Comment by leoslima13** [comment]
Hey @Kyle-Reis yes, it worked on a clean device and simulator, both scenarios worked (`LoginAndEnrollAccount` and `RegisterAndEnrollAccount` after get the MSAL auth). I did the tests separately, so it's all good.

I'll close this issue, and then we can discuss about .NET MAUI implementation for iOS in a specific topic
Thank you

**Comment by Kyle-Reis** [comment]
@leoslima13 - That's great! As a quick answer to your MAUI question: I'm an iOS expert, but I believe due to some technical limitations there is no current plan to support newer Android API versions for Xamarin.Android and the plan is instead to add support for newer Android versions via the new MAUI bindings. Someone from our Android SDK team should be able to help you if you have any more questions here. On the iOS side, we have not yet released support for MAUI but plan to do so before support for Xamarin.iOS ends.

**Comment by leoslima1** [comment]
Hey @Kyle-Reis do you know if something can help me to create the Binding for Android version? Xamarin.Forms, because I can't update my application to .net MAUI yet, since we don't have a package available for iOS

**Comment by Kyle-Reis** [comment]
Hi @leoslima1 - The iOS Intune MAM SDK MAUI binding is now available and can be found here:
https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.iOS
