### ISSUE TITLE
Help to create the new binding for Xamarin.Android that supports the latest version of Xamarin Forms (5.0)

### ISSUE THREAD

**Issue by leoslima1** [msintuneappsdk/intune-app-sdk-xamarin#62]
Can someone help me to create the MS Intune binding for Xamarin.Android that have support on the latest version?
Today we have Xamarin.IOS integrated, but we don't have support to the current version on Xamarin Android.
I noticed that already exists an integration for .net MAUI but only for iOS, do you guys are planning to have support to iOS too?
We are still holding the conversion to .NET MAUI because the MS Intune does not have support for iOS yet.

**Comment by Kyle-Reis** [comment]
Hi @leoslima1 - We are actively working on adding support for .Net MAUI for iOS.

**Comment by leoslima1** [comment]
Hey @Kyle-Reis awesome, do you know when we can start working with that, maybe a preview version? Or you guys are planning to support it when .net 8 comes?

**Comment by Kyle-Reis** [comment]
Hey @leoslima1 - Current ETA is end of October.

**Comment by meghandaly** [comment]
Resolving this as there is no planned work for bringing support to Xamarin.Forms for the latest Android OS versions. We encourage users to migrate MAUI and will update when iOS support is also available.

**Comment by gustavoja** [comment]
Hello @meghandaly even if we migrate to MAUI the Intune library is on Beta. How can we ship release versions to our clients with a beta and unstable version of a security library. 
Is there any ETA for the release version of the [Intune MAUI library](https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/) ?

**Comment by Kyle-Reis** [comment]
The Intune iOS MAM SDK MAUI binding is now available here:
https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.iOS
