### ISSUE TITLE
ADAL applications facing issues

### ISSUE THREAD

**Issue by MikeP0911** [msintuneappsdk/intune-app-sdk-xamarin#63]
Our app (Android) is using ADAL and not MSAL.
The migration could not be done to various dependencies and currently working on the migration to MAUI with MSAL.
Meanwhile there are customers who are facing issues.

Though it uses ADAL, according to the warning provided in the 
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-migration

the app should continue working without any problem.

**Warning

Azure Active Directory Authentication Library (ADAL) has been deprecated. While existing apps that use ADAL will continue to work, Microsoft will no longer release security fixes on ADAL. Use the [Microsoft Authentication Library (MSAL)](https://learn.microsoft.com/en-us/entra/msal/) to avoid putting your app's security at risk.**

But our customers are facing issues in it. All the customers had to reinstall all the applications in Android including company portal to make it work again.
If we do not reinstall the intune login does not happen.
Why is this happening.
For people where the app is working -- once uninstalled and re-installed, it stops working.
This situation forces us to again uninstall and re-install all the applications including the company portal.
This is a great pain to uninstall and re-install all the applications again and again.

**Comment by meghandaly** [comment]
@MikeP0911 Intune is not responsible for ADAL or MSAL. You should reach out to their respective teams.
