### ISSUE TITLE
Intune Xamarin Android SDK support for Android 13.

### ISSUE THREAD

**Issue by NiladriPadhy** [msintuneappsdk/intune-app-sdk-xamarin#64]
Hi,
We have a Xamarin.Android app and the app is being used by Intune Managed users, due to this the app is integrated with Intune SDK. We got a notification from Playstore to target the app to Android 13, but currently the recent version of intune Android SDK stop support from Android 10.
Currently we can't migrate the android app to MAUI, because the nuget packages which we are using not supporting MAUI. Due to this, we have to stick to Xamarin only unit all nuget packages supports MAUI. All production users got stuck with this issue

Please provide some work around solution to Integrate Intune Xamarin Android SDK, when app target to Android 13.

**Comment by meghandaly** [comment]
@NiladriPadhy While we empathize and wish there was an alternative, there is no workaround, and our guidance remains to migrate to MSAL.
