### ISSUE TITLE
Adding Microsoft.Intune.MAM.Xamarin.Android nuget package to Xamarin Forms Android app fails

### ISSUE THREAD

**Issue by rzdebskiy** [msintuneappsdk/intune-app-sdk-xamarin#8]
Adding Microsoft.Intune.MAM.Xamarin.Android nuget package to Xamarin Forms Android project fails with the following error:
NU1202: Package Microsoft.Intune.MAM.Xamarin.Android 3.0.3989.3 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package Microsoft.Intune.MAM.Xamarin.Android 3.0.3989.3 supports: net452xamarinandroid10 (net452+Xamarin.Android10,Version=v0.0)
Package restore failed. Rolling back package changes for 'IntuneSDKSample.Android'.

VS version: 15.6.6
Adding package fails both with Shared and .NET Standard project templates.

**Comment by reutann** [comment]
@rzdebskiy, sorry that you're experiencing this, I'll need to look into this further. Would you be able to provide the sample project? In the meantime, you should be able to manually edit the `packages.config` to include the package and manually create a reference to the DLL contained within it. You can open up the `.xam` file that's in this repo to see a full sample of integration with `Xamarin.Android` with/without `Xamarin.Forms`

**Comment by rzdebskiy** [comment]
It is just blank new Xamarin Forms project - https://github.com/rzdebskiy/IntuneSDKSample. When I try to add Microsoft.Intune.MAM.Xamarin.Android Nuget package to Android project I get:  
![image](https://user-images.githubusercontent.com/23632710/38856362-e6241346-422e-11e8-8b32-5fc1949108d2.png)

**Comment by rzdebskiy** [comment]
@reutann there is no packages.config in the project - please see source https://github.com/rzdebskiy/IntuneSDKSample. Maybe Microsoft.Intune.MAM.Xamarin.Android is not supported in Xamarin Forms projects?

**Comment by reutann** [comment]
@rzdebskiy, how are you downloading nuget packages without a packages.config? Are you using a different package manager? Microsoft.Intune.MAM.Xamarin.Android is definitely supported with Xamarin.Forms projects. 

To see a full sample of how to get this working, you can download [our .xam that contains samples](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/blob/master/Microsoft.Intune.MAM-3.0.0.0.xam) and mirror the configuration in your own project.

**Comment by reutann** [comment]
Looking a bit further into it, I can confirm that there is an issue with the target framework for the `Microsoft.Intune.MAM.Xamarin.Android` package that makes it incompatible with your project which is targeting `netstandard2.0`. While I the package is not truly incompatible, the target framework makes it impossible to include the package in your `netstandard2.0` project. We will need to take a change to support this _and_ to support using the `ProjectReference` element instead of packages.config. If you are able to drop your `TargetFramework`, you will be able to include the DLL.

**Comment by rzdebskiy** [comment]
Thank you @reutann - this is exactly my case - I use VS 2017 v15.6.6 which has new [Nuget reference format  ](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference). Could you advise on workaround for me while you are fixing this? Need a little bit more details on your piece of advice to *If you are able to drop your TargetFramework, you will be able to include the DLL*. I have tried to use Shared Project Template but got the same errors. Thank you in advance!

**Comment by arggrande** [comment]
@rzdebskiy regarding:
> If you are able to drop your TargetFramework, you will be able to include the DLL

Im think @reutann means drop the TargetFramework on the PCL/Shared Project to .Net Standard 1.3.

I think :)

**Comment by reutann** [comment]
We're shipping a fix to nuget.org today or Monday! Thanks for reporting this @rzdebskiy
