### ISSUE TITLE
remapping-config.json is missing after referencing Microsoft.Intune.MAM.Remapper.Tasks 

### ISSUE THREAD

**Issue by rzdebskiy** [msintuneappsdk/intune-app-sdk-xamarin#9]
I am using [Microsoft Intune App SDK Xamarin Bindings](https://docs.microsoft.com/en-us/intune/app-sdk-xamarin) guide to integrate Intune SDK with Xamarin Forms app. 
When I reference Nuget package [Microsoft.Intune.MAM.Remapper.Task](https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.Android) as advised in the guide it references successfuly but no remapping-config.json file is added to the project. Here is sample project - https://github.com/rzdebskiy/IntuneSDKSample .

**Comment by reutann** [comment]
According to the sample project that you've shared, https://github.com/rzdebskiy/IntuneSDKSample/blob/master/IntuneSDKSample/IntuneSDKSample.Android/IntuneSDKSample.Android.csproj shows no sign of including the remapper tasks and, also, the link that you've posted and labeled as "Microsoft.Intune.MAM.Remapper.Task" is actually the bindings DLLs, not the remapper tasks. You can see the Remapper tasks here: https://www.nuget.org/packages/Microsoft.Intune.MAM.Remapper.Tasks/

To see a full sample of how to get this working, you can download [our .xam that contains samples](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/blob/master/Microsoft.Intune.MAM-3.0.0.0.xam) and mirror the configuration in your own project. 

Closing for now as the sample should give you enough guidance to get your app into a working state.

**Comment by rzdebskiy** [comment]
Thank you @reutann , I have VS 2017 v15.6.6 when I try to `xamarin-component.exe install .\Microsoft.Intune.MAM-3.0.0.0.xam ` 
I get an error: 
`Unhandled Exception: ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Xamarin.Components.Packaging.ComponentPackage..ctor(String file)
   at Xamarin.Components.InstallCommandHandler.Invoke(String[] args)
   at Xamarin.Components.MainClass.Main(String[] args)`

Do you samples in archive with *.sln (Visua Studio Solution) files? Thank you in advance.

**Comment by reutann** [comment]
Unfortunately, Xamarin has removed support for the Component store for new projects so until we can get those samples up on github, you'll need to extract the xam (it's just an archive) and view the samples that way.
